/* eslint-disable @typescript-eslint/no-explicit-any */
import { BaseProcessor } from './base-processor'
import {
    SLOT,
    type ProcessorDef,
    type IDataflowEngine,
    type EventSignal,
    type ContourSamples,
} from '../types'

export const tapZoneDef: ProcessorDef = {
    type: 'tapZone',
    title: 'Tap Zone',
    category: 'animTrigger',
    inputs: [
        // Clickable region in scene-pixel space; Tier-3 hit-tests taps against this contour.
        { name: 'contour', type: SLOT.CONTOUR },
    ],
    outputs: [{ name: 'event', type: SLOT.EVENT }],
    defaultParams: {
        // Tier-3 dispatch slug; derivePublishedSurface rejects duplicates. Empty default
        // forces the author to set one (autogenerated tap_<n> by addProcessorNode).
        id: '',
        label: 'Tap zone',
        hint: '',
    },
}

// alwaysDirty so downstream sees the freshest event.count each frame. Editor's EMIT
// button fires events regardless of whether the contour is wired (hard dep at publish).
export class TapZoneProcessor extends BaseProcessor {
    readonly def = tapZoneDef
    alwaysDirty = true

    state: EventSignal = { count: 0, lastTimestampMs: 0 }
    contour: ContourSamples | null = null

    // Optional (x, y) reach downstream via EventSignal.lastX/lastY for hit-positioned animations.
    emit(x?: number, y?: number): void {
        const now = performance.now()
        this.state = {
            count: this.state.count + 1,
            lastTimestampMs: now,
            lastX: x,
            lastY: y,
        }
    }

    execute(inputs: Record<string, any>, _params: Record<string, any>, _engine: IDataflowEngine): Record<string, any> {
        this.contour = (inputs.contour as ContourSamples | null) ?? null
        return { event: { ...this.state } }
    }
}
