/* eslint-disable @typescript-eslint/no-explicit-any */
import { BaseProcessor } from './base-processor'
import {
    SLOT,
    type ProcessorDef,
    type IDataflowEngine,
    type EventSignal,
    type ContourSamples,
} from '../types'

export const tapZoneDef: ProcessorDef = {
    type: 'tapZone',
    title: 'Tap Zone',
    category: 'animTrigger',
    inputs: [
        /* Defines the clickable region in scene-pixel space. The Tier-3
           runtime hit-tests user taps against this contour; in the
           editor the contour is just an upstream dependency that the
           preview canvas can use to draw the zone's outline. */
        { name: 'contour', type: SLOT.CONTOUR },
    ],
    outputs: [{ name: 'event', type: SLOT.EVENT }],
    defaultParams: {
        /* Stable identifier the Tier-3 client uses to dispatch events.
           Required by the publish validator (`derivePublishedSurface`
           reports duplicates as a hard error). Default empty string so
           the author is forced to set one — autogenerated tap_<id> is
           supplied by `addProcessorNode` at creation time. */
        id: '',
        /* Supplier-facing label. Not required for publish (falls back
           to `data.label` or processor title). */
        label: 'Tap zone',
        /* Optional supplier-facing tooltip. */
        hint: '',
    },
}

/**
 * Tier-3 tap-zone source. In the runtime, the platform's touch
 * handler hit-tests against the connected `contour` and calls `emit()`
 * on the corresponding processor instance whenever a tap lands inside.
 *
 * In the editor, the node card surfaces an EMIT button (same pattern
 * as `eventEmitter`) so the author can exercise downstream chains
 * (Envelope, SignalSwitch, AnimationSwitch) without wiring a real
 * canvas listener — the contour input is a hard dependency for
 * publish, but events fire from the button regardless of whether the
 * contour is wired.
 *
 * `alwaysDirty = true` so downstream consumers see the freshest
 * `event.count` every frame.
 */
export class TapZoneProcessor extends BaseProcessor {
    readonly def = tapZoneDef
    alwaysDirty = true

    state: EventSignal = { count: 0, lastTimestampMs: 0 }
    /** Most recent CONTOUR seen — used by the view to draw the zone
     *  outline if any preview is added later. Treated as opaque. */
    contour: ContourSamples | null = null

    /** Programmatic API for any UI / runtime bridge to push an event.
     *  Optional `(x, y)` are surfaced to downstream consumers via
     *  `EventSignal.lastX/lastY` for hit-positioned animations. */
    emit(x?: number, y?: number): void {
        const now = performance.now()
        this.state = {
            count: this.state.count + 1,
            lastTimestampMs: now,
            lastX: x,
            lastY: y,
        }
    }

    execute(inputs: Record<string, any>, _params: Record<string, any>, _engine: IDataflowEngine): Record<string, any> {
        this.contour = (inputs.contour as ContourSamples | null) ?? null
        return { event: { ...this.state } }
    }
}
