import fragment from './fragment'
import type { PlaygroundConfig } from '../../pipeline/types'
import { copySourcePass } from '../../pipeline/passes/copy-source'

export const config: PlaygroundConfig = {
    name: 'TextGridOrbit',
    canvas: { width: 900, height: 1200 },
    passes: [
        copySourcePass,
        { id: 'main', kind: 'fullscreen', blend: 'add', fragment, requiresInputs: ['sdf', 'atlas'] },
    ],
    fields: [
        {
            name: 'uOrbitCenter',
            label: 'Orbit center (px)',
            kind: 'f32',
            default: 80,
            slider: { min: 10, max: 400, step: 1 },
        },
        {
            name: 'uOrbitAmplitude',
            label: 'Orbit amplitude (px)',
            kind: 'f32',
            default: 60,
            slider: { min: 0, max: 300, step: 1 },
        },
        {
            name: 'uOrbitSpeed',
            label: 'Orbit speed',
            kind: 'f32',
            default: 0.8,
            slider: { min: 0.1, max: 5.0, step: 0.1 },
        },
        {
            name: 'uOrbitWidth',
            label: 'Orbit band width (px)',
            kind: 'f32',
            default: 150,
            slider: { min: 10, max: 500, step: 1 },
        },
        {
            name: 'uStepInterval',
            label: 'Step interval (s)',
            kind: 'f32',
            default: 0.15,
            slider: { min: 0.03, max: 1.0, step: 0.01 },
        },
        {
            name: 'uGridSize',
            label: 'Grid cell size (px)',
            kind: 'f32',
            default: 40,
            slider: { min: 10, max: 120, step: 1 },
        },
        {
            name: 'uSegmentMargin',
            label: 'Segment margin (px)',
            kind: 'f32',
            default: 5.0,
            slider: { min: 0, max: 50, step: 1 },
        },
        {
            name: 'uGlyphScale',
            label: 'Glyph scale',
            kind: 'f32',
            default: 0.85,
            slider: { min: 0.3, max: 1.0, step: 0.01 },
        },
        {
            name: 'uGlyphCount',
            label: 'Glyph variety (1-16)',
            kind: 'f32',
            default: 16,
            slider: { min: 1, max: 16, step: 1 },
        },
        {
            name: 'uDotColor',
            label: 'Glyph color',
            kind: 'vec4<f32>',
            color: true,
            default: [0.1, 1.0, 0.3, 1.0],
            slider: { min: 0, max: 1, step: 0.01 },
        },
        {
            name: 'uGlowColor',
            label: 'Glow color',
            kind: 'vec4<f32>',
            color: true,
            default: [0.0, 0.8, 0.2, 1.0],
            slider: { min: 0, max: 1, step: 0.01 },
        },
        {
            name: 'uGlowSpread',
            label: 'Glow spread',
            kind: 'f32',
            default: 3.0,
            slider: { min: 0.5, max: 10.0, step: 0.1 },
        },
        {
            name: 'uGlowIntensity',
            label: 'Glow intensity',
            kind: 'f32',
            default: 0.6,
            slider: { min: 0.0, max: 2.0, step: 0.05 },
        },
        {
            name: 'uNoiseAmount',
            label: 'Wave noise amount (px)',
            kind: 'f32',
            default: 25,
            slider: { min: 0, max: 100, step: 1 },
        },
        {
            name: 'uNoiseScale',
            label: 'Noise scale',
            kind: 'f32',
            default: 1.0,
            slider: { min: 0.1, max: 5.0, step: 0.1 },
        },
        {
            name: 'uFalloff',
            label: 'Distance falloff',
            kind: 'f32',
            default: 0.005,
            slider: { min: 0.0, max: 0.05, step: 0.001 },
        },
        {
            name: 'uDepthSoftness',
            label: 'Depth softness',
            kind: 'f32',
            default: 0.1,
            slider: { min: 0.01, max: 0.5, step: 0.01 },
        },
    ],
    animation: {
        slots: [
            { slot: 0, label: 'Scroll (sec)',         defaultMin: 0, defaultMax: 6 },
            { slot: 1, label: 'Radial offset (px)',   defaultMin: 0, defaultMax: 60 },
            { slot: 3, label: 'Glow multiplier',      defaultMin: 1, defaultMax: 2 },
            { slot: 4, label: 'Intensity multiplier', defaultMin: 1, defaultMax: 1 },
        ],
    },
}
