import fragment from './fragment'
import type { PlaygroundConfig } from '../../pipeline/types'
import { copySourcePass } from '../../pipeline/passes/copy-source'

export const config: PlaygroundConfig = {
    name: 'DropGridOrbit',
    canvas: { width: 900, height: 1200 },
    passes: [
        copySourcePass,
        { id: 'main', kind: 'fullscreen', blend: 'normal', fragment, requiresInputs: ['sdf'] },
    ],
    fields: [
        {
            name: 'uOrbitCenter',
            label: 'Orbit center (px)',
            kind: 'f32',
            default: 80,
            slider: { min: 10, max: 400, step: 1 },
        },
        {
            name: 'uOrbitAmplitude',
            label: 'Orbit amplitude (px)',
            kind: 'f32',
            default: 60,
            slider: { min: 0, max: 300, step: 1 },
        },
        {
            name: 'uOrbitSpeed',
            label: 'Orbit speed',
            kind: 'f32',
            default: 1.2,
            slider: { min: 0.1, max: 5.0, step: 0.1 },
        },
        {
            name: 'uOrbitWidth',
            label: 'Orbit band width (px)',
            kind: 'f32',
            default: 120,
            slider: { min: 10, max: 500, step: 1 },
        },
        {
            name: 'uGridSize',
            label: 'Grid cell size (px)',
            kind: 'f32',
            default: 28,
            slider: { min: 6, max: 80, step: 1 },
        },
        {
            name: 'uDotMaxRadius',
            label: 'Drop max radius (px)',
            kind: 'f32',
            default: 10,
            slider: { min: 1, max: 30, step: 0.5 },
        },
        {
            name: 'uDotMinRadius',
            label: 'Drop min radius (px)',
            kind: 'f32',
            default: 1.5,
            slider: { min: 0.5, max: 10, step: 0.5 },
        },
        {
            name: 'uSegmentMargin',
            label: 'Segment margin (px)',
            kind: 'f32',
            default: 5.0,
            slider: { min: 0, max: 50, step: 1 },
        },
        {
            name: 'uRefraction',
            label: 'Refraction strength',
            kind: 'f32',
            default: 0.6,
            slider: { min: 0.0, max: 2.0, step: 0.01 },
        },
        {
            name: 'uIOR',
            label: 'Index of refraction',
            kind: 'f32',
            default: 1.33,
            slider: { min: 1.0, max: 2.5, step: 0.01 },
        },
        {
            name: 'uFresnelPower',
            label: 'Fresnel power',
            kind: 'f32',
            default: 3.0,
            slider: { min: 0.5, max: 10.0, step: 0.1 },
        },
        {
            name: 'uFresnelIntensity',
            label: 'Fresnel intensity',
            kind: 'f32',
            default: 0.6,
            slider: { min: 0.0, max: 2.0, step: 0.01 },
        },
        {
            name: 'uSpecularPower',
            label: 'Specular power',
            kind: 'f32',
            default: 32.0,
            slider: { min: 4, max: 128, step: 1 },
        },
        {
            name: 'uSpecularIntensity',
            label: 'Specular intensity',
            kind: 'f32',
            default: 0.8,
            slider: { min: 0.0, max: 3.0, step: 0.01 },
        },
        {
            name: 'uAberration',
            label: 'Chromatic aberration',
            kind: 'f32',
            default: 0.04,
            slider: { min: 0.0, max: 0.15, step: 0.005 },
        },
        {
            name: 'uShadowRadius',
            label: 'Shadow radius (px)',
            kind: 'f32',
            default: 4.0,
            slider: { min: 0, max: 15, step: 0.5 },
        },
        {
            name: 'uShadowOpacity',
            label: 'Shadow opacity',
            kind: 'f32',
            default: 0.25,
            slider: { min: 0.0, max: 0.8, step: 0.01 },
        },
        {
            name: 'uRimDarkWidth',
            label: 'Rim dark width',
            kind: 'f32',
            default: 0.3,
            slider: { min: 0.0, max: 0.6, step: 0.01 },
        },
        {
            name: 'uRimDarkIntensity',
            label: 'Rim dark intensity',
            kind: 'f32',
            default: 0.4,
            slider: { min: 0.0, max: 1.0, step: 0.01 },
        },
        {
            name: 'uEnvIntensity',
            label: 'Env reflection',
            kind: 'f32',
            default: 0.35,
            slider: { min: 0.0, max: 1.0, step: 0.01 },
        },
        {
            name: 'uEnvTint',
            label: 'Env tint',
            kind: 'vec4<f32>',
            color: true,
            default: [0.9, 0.95, 1.0, 1.0],
            slider: { min: 0, max: 1, step: 0.01 },
        },
        {
            name: 'uEnvBlur',
            label: 'Env blur',
            kind: 'f32',
            default: 0.3,
            slider: { min: 0.0, max: 2.0, step: 0.01 },
        },
        {
            name: 'uNoiseAmount',
            label: 'Wave noise amount (px)',
            kind: 'f32',
            default: 25,
            slider: { min: 0, max: 100, step: 1 },
        },
        {
            name: 'uNoiseScale',
            label: 'Noise scale',
            kind: 'f32',
            default: 1.0,
            slider: { min: 0.1, max: 5.0, step: 0.1 },
        },
        {
            name: 'uFalloff',
            label: 'Distance falloff',
            kind: 'f32',
            default: 0.005,
            slider: { min: 0.0, max: 0.05, step: 0.001 },
        },
        {
            name: 'uEdgeSoftness',
            label: 'Edge softness',
            kind: 'f32',
            default: 0.15,
            slider: { min: 0.0, max: 2.0, step: 0.01 },
        },
        {
            name: 'uDepthSoftness',
            label: 'Depth softness',
            kind: 'f32',
            default: 0.1,
            slider: { min: 0.01, max: 0.5, step: 0.01 },
        },
    ],
    animation: {
        slots: [
            { slot: 0, label: 'Scroll (sec)',         defaultMin: 0, defaultMax: 6 },
            { slot: 1, label: 'Radial offset (px)',   defaultMin: 0, defaultMax: 60 },
            { slot: 4, label: 'Intensity multiplier', defaultMin: 1, defaultMax: 1 },
        ],
    },
}
