import fragment from './fragment'
import type { PlaygroundConfig } from '../../pipeline/types'
import { copySourcePass } from '../../pipeline/passes/copy-source'

export const config: PlaygroundConfig = {
    name: 'GlowDropOrbit',
    canvas: { width: 900, height: 1200 },
    passes: [
        copySourcePass,
        { id: 'main', kind: 'fullscreen', blend: 'normal', fragment, requiresInputs: ['sdf'] },
    ],
    fields: [
        {
            name: 'uOrbitCenter',
            label: 'Orbit center (px)',
            kind: 'f32',
            default: 80,
            slider: { min: 10, max: 400, step: 1 },
        },
        {
            name: 'uOrbitAmplitude',
            label: 'Orbit amplitude (px)',
            kind: 'f32',
            default: 60,
            slider: { min: 0, max: 300, step: 1 },
        },
        {
            name: 'uOrbitSpeed',
            label: 'Orbit speed',
            kind: 'f32',
            default: 1.2,
            slider: { min: 0.1, max: 5.0, step: 0.1 },
        },
        {
            name: 'uOrbitWidth',
            label: 'Orbit band width (px)',
            kind: 'f32',
            default: 120,
            slider: { min: 10, max: 500, step: 1 },
        },
        {
            name: 'uGridSize',
            label: 'Grid cell size (px)',
            kind: 'f32',
            default: 18,
            slider: { min: 6, max: 80, step: 1 },
        },
        {
            name: 'uDropBaseRadius',
            label: 'Drop base radius (px)',
            kind: 'f32',
            default: 5.0,
            slider: { min: 0.5, max: 20, step: 0.1 },
        },
        {
            name: 'uDropPulseAmp',
            label: 'Drop pulse amp (px)',
            kind: 'f32',
            default: 2.0,
            slider: { min: 0, max: 10, step: 0.1 },
        },
        {
            name: 'uDropPulseFreq',
            label: 'Drop pulse freq',
            kind: 'f32',
            default: 5.0,
            slider: { min: 0.1, max: 20, step: 0.1 },
        },
        {
            name: 'uDropPulseSpeed',
            label: 'Drop pulse speed',
            kind: 'f32',
            default: 3.0,
            slider: { min: 0.0, max: 10, step: 0.1 },
        },
        {
            name: 'uDropMinRadius',
            label: 'Drop min radius (px)',
            kind: 'f32',
            default: 1.2,
            slider: { min: 0.1, max: 10, step: 0.1 },
        },
        {
            name: 'uSegmentMargin',
            label: 'Segment margin (px)',
            kind: 'f32',
            default: 5.0,
            slider: { min: 0, max: 50, step: 1 },
        },
        {
            name: 'uColorA',
            label: 'Color A (pink)',
            kind: 'vec4<f32>',
            color: true,
            default: [1.0, 0.42, 0.78, 1.0],
            slider: { min: 0, max: 1, step: 0.01 },
        },
        {
            name: 'uColorB',
            label: 'Color B (purple)',
            kind: 'vec4<f32>',
            color: true,
            default: [0.64, 0.39, 1.0, 1.0],
            slider: { min: 0, max: 1, step: 0.01 },
        },
        {
            name: 'uColorFreq',
            label: 'Color freq',
            kind: 'f32',
            default: 3.0,
            slider: { min: 0.1, max: 20, step: 0.1 },
        },
        {
            name: 'uColorSpeed',
            label: 'Color speed',
            kind: 'f32',
            default: 1.6,
            slider: { min: 0.0, max: 10, step: 0.1 },
        },
        {
            name: 'uGlowSpread',
            label: 'Glow spread (px)',
            kind: 'f32',
            default: 14.0,
            slider: { min: 1, max: 40, step: 0.5 },
        },
        {
            name: 'uGlowIntensity',
            label: 'Glow intensity',
            kind: 'f32',
            default: 0.8,
            slider: { min: 0.0, max: 2.0, step: 0.01 },
        },
        {
            name: 'uCoreIntensity',
            label: 'Core intensity',
            kind: 'f32',
            default: 1.0,
            slider: { min: 0.0, max: 2.0, step: 0.01 },
        },
        {
            name: 'uEdgeSoftness',
            label: 'Edge softness (px)',
            kind: 'f32',
            default: 0.8,
            slider: { min: 0.1, max: 3.0, step: 0.05 },
        },
        {
            name: 'uFalloff',
            label: 'Distance falloff',
            kind: 'f32',
            default: 0.004,
            slider: { min: 0.0, max: 0.05, step: 0.001 },
        },
        {
            name: 'uNoiseAmount',
            label: 'Wave noise amount (px)',
            kind: 'f32',
            default: 20,
            slider: { min: 0, max: 100, step: 1 },
        },
        {
            name: 'uNoiseScale',
            label: 'Noise scale',
            kind: 'f32',
            default: 1.0,
            slider: { min: 0.1, max: 5.0, step: 0.1 },
        },
        {
            name: 'uDepthSoftness',
            label: 'Depth softness',
            kind: 'f32',
            default: 0.1,
            slider: { min: 0.01, max: 0.5, step: 0.01 },
        },
    ],
    animation: {
        slots: [
            { slot: 0, label: 'Scroll (sec)',         defaultMin: 0, defaultMax: 6 },
            { slot: 1, label: 'Radial offset (px)',   defaultMin: 0, defaultMax: 60 },
            { slot: 2, label: 'Size multiplier',      defaultMin: 1, defaultMax: 2 },
            { slot: 3, label: 'Glow multiplier',      defaultMin: 1, defaultMax: 2 },
            { slot: 4, label: 'Intensity multiplier', defaultMin: 1, defaultMax: 1 },
        ],
    },
}
