import fragment from './fragment'
import type { PlaygroundConfig } from '../../pipeline/types'
import { copySourcePass } from '../../pipeline/passes/copy-source'

export const config: PlaygroundConfig = {
    name: 'NeonRingOrbit',
    canvas: { width: 900, height: 1200 },
    passes: [
        copySourcePass,
        { id: 'main', kind: 'fullscreen', blend: 'normal', fragment, requiresInputs: ['sdf'] },
    ],
    fields: [
        {
            name: 'uOrbitCenter',
            label: 'Orbit center (px)',
            kind: 'f32',
            default: 80,
            slider: { min: 10, max: 400, step: 1 },
        },
        {
            name: 'uOrbitAmplitude',
            label: 'Orbit amplitude (px)',
            kind: 'f32',
            default: 60,
            slider: { min: 0, max: 300, step: 1 },
        },
        {
            name: 'uOrbitSpeed',
            label: 'Orbit speed',
            kind: 'f32',
            default: 0.8,
            slider: { min: 0.1, max: 5.0, step: 0.1 },
        },
        {
            name: 'uOrbitWidth',
            label: 'Orbit band width (px)',
            kind: 'f32',
            default: 150,
            slider: { min: 10, max: 500, step: 1 },
        },
        {
            name: 'uGridSize',
            label: 'Grid cell size (px)',
            kind: 'f32',
            default: 32,
            slider: { min: 6, max: 100, step: 1 },
        },
        {
            name: 'uDotMaxRadius',
            label: 'Ring max radius (px)',
            kind: 'f32',
            default: 12,
            slider: { min: 1, max: 40, step: 0.5 },
        },
        {
            name: 'uDotMinRadius',
            label: 'Ring min radius (px)',
            kind: 'f32',
            default: 1.5,
            slider: { min: 0.5, max: 10, step: 0.5 },
        },
        {
            name: 'uSegmentMargin',
            label: 'Segment margin (px)',
            kind: 'f32',
            default: 5.0,
            slider: { min: 0, max: 50, step: 1 },
        },
        {
            name: 'uRingThickness',
            label: 'Ring thickness (px)',
            kind: 'f32',
            default: 1.5,
            slider: { min: 0.3, max: 6.0, step: 0.1 },
        },
        {
            name: 'uGlowSpread',
            label: 'Glow spread (px)',
            kind: 'f32',
            default: 6.0,
            slider: { min: 1, max: 25, step: 0.5 },
        },
        {
            name: 'uGlowIntensity',
            label: 'Glow intensity',
            kind: 'f32',
            default: 0.5,
            slider: { min: 0.0, max: 1.5, step: 0.01 },
        },
        {
            name: 'uRingColor',
            label: 'Ring color',
            kind: 'vec4<f32>',
            color: true,
            default: [0.1, 0.9, 1.0, 1.0],
            slider: { min: 0, max: 1, step: 0.01 },
        },
        {
            name: 'uGlowColor',
            label: 'Glow color',
            kind: 'vec4<f32>',
            color: true,
            default: [0.05, 0.5, 0.8, 1.0],
            slider: { min: 0, max: 1, step: 0.01 },
        },
        {
            name: 'uLineWidth',
            label: 'Line width (px)',
            kind: 'f32',
            default: 0.8,
            slider: { min: 0.1, max: 4.0, step: 0.1 },
        },
        {
            name: 'uLineGlow',
            label: 'Line glow (px)',
            kind: 'f32',
            default: 3.0,
            slider: { min: 0.5, max: 15.0, step: 0.5 },
        },
        {
            name: 'uLineIntensity',
            label: 'Line intensity',
            kind: 'f32',
            default: 0.3,
            slider: { min: 0.0, max: 1.0, step: 0.01 },
        },
        {
            name: 'uNoiseAmount',
            label: 'Wave noise amount (px)',
            kind: 'f32',
            default: 25,
            slider: { min: 0, max: 100, step: 1 },
        },
        {
            name: 'uNoiseScale',
            label: 'Noise scale',
            kind: 'f32',
            default: 1.0,
            slider: { min: 0.1, max: 5.0, step: 0.1 },
        },
        {
            name: 'uFalloff',
            label: 'Distance falloff',
            kind: 'f32',
            default: 0.005,
            slider: { min: 0.0, max: 0.05, step: 0.001 },
        },
        {
            name: 'uDepthSoftness',
            label: 'Depth softness',
            kind: 'f32',
            default: 0.1,
            slider: { min: 0.01, max: 0.5, step: 0.01 },
        },
    ],
    animation: {
        class: 'orbital-particles',
        channels: [
            { id: 'scroll',    label: 'Scroll (sec)',         defaultMin: 0, defaultMax: 6 },
            { id: 'radial',    label: 'Radial offset (px)',   defaultMin: 0, defaultMax: 60 },
            { id: 'size',      label: 'Size multiplier',      defaultMin: 1, defaultMax: 2 },
            { id: 'glow',      label: 'Glow multiplier',      defaultMin: 1, defaultMax: 2 },
            { id: 'intensity', label: 'Intensity multiplier', defaultMin: 1, defaultMax: 1 },
        ],
    },
}
